<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>QuickTranslate.TextToSpeech</RootNamespace>
    <AssemblyName>QuickTranslate.TextToSpeech</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Speech" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>