<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>QuickTranslate.Platform</RootNamespace>
    <AssemblyName>QuickTranslate.Platform</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.*" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.*" />
    <ProjectReference Include="..\QuickTranslate.Core\QuickTranslate.Core.csproj" />
  </ItemGroup>
</Project>
